export const API_ENDPOINTS = {
  auth: {
    login: "/auth/login",
    signup: "/auth/signup",
    getMe: "/auth/me",
    forgotPassword: "/auth/forgotPassword",
    resetPassword: "/auth/resetPassword",
    verifyOTP: "/auth/verifyOTP",
    changePassword: "/auth/changePassword",
    logout: "/auth/logout",
    refreshToken: "/auth/refreshToken",
    verifyToken: "/auth/verifyToken",
    sendSignUpOTP: "auth/sendSignUpOTP",
  },
  patients: {
    profile: "/patients/profile",
    patientDetailForm: "/patients/patientDetailForm",
    patientInfoUpdate: "/patients/info/update",
    popularDoctors: "/patients/popularDoctors",
    searchDoctorByName: "/patients/search/doctors/name",
    searchDoctorBySpecialty: (specialty) =>
      `/patients/search/${specialty}/name`,
    filterBySpecialty: (specialty) => `/patients/search/${specialty}`,
    viewDoctorProfile: (doctorId) => `/patients/doctor/${doctorId}`,
    doctorReview: (doctorId) => `/patients/review/${doctorId}`,
    getUpcomingConsultations: "/patients/consultations/upcoming",
    getPastConsultations: "/patients/consultations/past",
    viewConsultationNote: (id) => `/patients/consultations/note/${id}`,
    createConsultation: (doctorId) =>
      `/patients/consultations/booking/${doctorId}`,
  },
  doctors: {
    verifyIdentity: "/doctors/verifyIdentity",
    // home: '/doctors/home',
    getUpcomingConsultations: "/doctors/consultations/upcoming",
    getPastConsultations: "/doctors/consultations/past",
    getConsultationDetails: (id) => `/doctors/consultation/details/${id}`,
    cancelConsultation: (id) => `/doctors/consultations/cancel/${id}`,
    viewConsultationNotes: (id) => `/doctors/consultation/note/${id}`,
    profile: "/doctors/profile",
    // notifications: '/doctors/notifications',
    viewSchedule: (doctorId) => `/doctors/schedule/${doctorId}`,
    createSchedule: `/doctors/schedule/create`,
    // deleteSchedule: (scheduleId) => `/doctors/schedule/delete/${scheduleId}`,
    profileUpdate: "/doctors/profile/update",
    popularDoctors: "/doctors/popularDoctors",
    viewPatientDetails: (id) => `/doctors/user/details/${id}`,
  },
};
